bot {
    token = ${?BOT_TOKEN}
    username = ${?BOT_USERNAME}
}

webapp {
    port = 8080
    port = ${?WEBAPP_PORT}
    url = "http://localhost:8080"
    url = ${?WEBAPP_URL}
}

database {
    jdbcUrl = "jdbc:postgresql://localhost:5432/meventus"
    jdbcUrl = ${?DATABASE_URL}
    username = "meventus"
    username = ${?DATABASE_USER}
    password = "meventus"
    password = ${?DATABASE_PASSWORD}
    maxPoolSize = 10
}
