bot {
    token = ${?BOT_TOKEN}
    username = ${?BOT_USERNAME}
}

database {
    jdbcUrl = "jdbc:postgresql://localhost:5432/meventus"
    jdbcUrl = ${?DATABASE_URL}
    username = "meventus"
    username = ${?DATABASE_USER}
    password = "meventus"
    password = ${?DATABASE_PASSWORD}
    maxPoolSize = 10
}
